
server {

  listen 80;

  listen [::]:80;

  server_name studioundesignated.com www.studioundesignated.com;



  # Let's Encrypt 갱신용 (HTTP에서만)

  location ^~ /.well-known/acme-challenge/ {

    root /var/www/letsencrypt;

    default_type "text/plain";

    try_files $uri =404;

    allow all;

  }



  # 모든 HTTP 요청을 루트 HTTPS로 통일

  location / {

    return 301 https://studioundesignated.com$request_uri;

  }

}

