
# 1) www -> root 로 리다이렉트

server {

  listen 443 ssl;

  listen [::]:443 ssl;

  server_name www.studioundesignated.com;



  ssl_certificate     /etc/letsencrypt/live/studioundesignated.com/fullchain.pem;

  ssl_certificate_key /etc/letsencrypt/live/studioundesignated.com/privkey.pem;



  return 301 https://studioundesignated.com$request_uri;

}



# 2) root 도메인에서 실제 서비스

server {

  listen 443 ssl;

  listen [::]:443 ssl;

  server_name studioundesignated.com;



  ssl_certificate     /etc/letsencrypt/live/studioundesignated.com/fullchain.pem;

  ssl_certificate_key /etc/letsencrypt/live/studioundesignated.com/privkey.pem;



  ssl_session_cache shared:SSL:10m;

  ssl_session_timeout 10m;

  ssl_protocols TLSv1.2 TLSv1.3;



  root /usr/share/nginx/html;

  index index.html;



  location / {

    try_files $uri $uri/ /index.html;

  }

}

